# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 067ce14f64118f85598971e5ed51386263c235e789b2a95cac6c42caf4402079f585d1baf1d36a5444ba5fda61f4790678ff81305e34b90a27edefc0149e0902

test:
  secret_key_base: 07d61a9520d171a032bcd90db93c2b828441375952983b8f739e8ef69d5917bc5c392175f4aa3eedd7f5a93dd326f8519af14e944a58939b9ab47cdd2d076a27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
